// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/conf/alfy.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alfy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Alfy_Items `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Alfy) Reset() {
	*x = Alfy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_alfy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alfy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alfy) ProtoMessage() {}

func (x *Alfy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_alfy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alfy.ProtoReflect.Descriptor instead.
func (*Alfy) Descriptor() ([]byte, []int) {
	return file_internal_conf_alfy_proto_rawDescGZIP(), []int{0}
}

func (x *Alfy) GetItems() []*Alfy_Items {
	if x != nil {
		return x.Items
	}
	return nil
}

type Alfy_Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          string                     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type         string                     `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title        string                     `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle     string                     `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Arg          string                     `protobuf:"bytes,5,opt,name=arg,proto3" json:"arg,omitempty"`
	Autocomplete string                     `protobuf:"bytes,6,opt,name=autocomplete,proto3" json:"autocomplete,omitempty"`
	Icon         *Alfy_Items_Icon           `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Valid        bool                       `protobuf:"varint,8,opt,name=valid,proto3" json:"valid,omitempty"`
	Match        string                     `protobuf:"bytes,9,opt,name=match,proto3" json:"match,omitempty"`
	Mods         map[string]*Alfy_Items_Mod `protobuf:"bytes,10,rep,name=mods,proto3" json:"mods,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Quicklookurl string                     `protobuf:"bytes,11,opt,name=quicklookurl,proto3" json:"quicklookurl,omitempty"`
	Text         map[string]string          `protobuf:"bytes,12,rep,name=text,proto3" json:"text,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Alfy_Items) Reset() {
	*x = Alfy_Items{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_alfy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alfy_Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alfy_Items) ProtoMessage() {}

func (x *Alfy_Items) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_alfy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alfy_Items.ProtoReflect.Descriptor instead.
func (*Alfy_Items) Descriptor() ([]byte, []int) {
	return file_internal_conf_alfy_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Alfy_Items) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Alfy_Items) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Alfy_Items) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alfy_Items) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Alfy_Items) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *Alfy_Items) GetAutocomplete() string {
	if x != nil {
		return x.Autocomplete
	}
	return ""
}

func (x *Alfy_Items) GetIcon() *Alfy_Items_Icon {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *Alfy_Items) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *Alfy_Items) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *Alfy_Items) GetMods() map[string]*Alfy_Items_Mod {
	if x != nil {
		return x.Mods
	}
	return nil
}

func (x *Alfy_Items) GetQuicklookurl() string {
	if x != nil {
		return x.Quicklookurl
	}
	return ""
}

func (x *Alfy_Items) GetText() map[string]string {
	if x != nil {
		return x.Text
	}
	return nil
}

type Alfy_Items_Mod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg      string `protobuf:"bytes,1,opt,name=arg,proto3" json:"arg,omitempty"`
	Subtitle string `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Alfy_Items_Mod) Reset() {
	*x = Alfy_Items_Mod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_alfy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alfy_Items_Mod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alfy_Items_Mod) ProtoMessage() {}

func (x *Alfy_Items_Mod) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_alfy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alfy_Items_Mod.ProtoReflect.Descriptor instead.
func (*Alfy_Items_Mod) Descriptor() ([]byte, []int) {
	return file_internal_conf_alfy_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Alfy_Items_Mod) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *Alfy_Items_Mod) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Alfy_Items_Mod) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Alfy_Items_Icon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Alfy_Items_Icon) Reset() {
	*x = Alfy_Items_Icon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_alfy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alfy_Items_Icon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alfy_Items_Icon) ProtoMessage() {}

func (x *Alfy_Items_Icon) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_alfy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alfy_Items_Icon.ProtoReflect.Descriptor instead.
func (*Alfy_Items_Icon) Descriptor() ([]byte, []int) {
	return file_internal_conf_alfy_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Alfy_Items_Icon) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Alfy_Items_Icon) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_internal_conf_alfy_proto protoreflect.FileDescriptor

var file_internal_conf_alfy_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f,
	0x61, 0x6c, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x6e, 0x66,
	0x22, 0xa4, 0x05, 0x0a, 0x04, 0x41, 0x6c, 0x66, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e,
	0x41, 0x6c, 0x66, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x1a, 0xf3, 0x04, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x72, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74,
	0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41,
	0x6c, 0x66, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x2e, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41, 0x6c, 0x66, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x2e, 0x4d, 0x6f, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x72, 0x6c,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x6c, 0x6f, 0x6f,
	0x6b, 0x75, 0x72, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0c, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41, 0x6c, 0x66, 0x79, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x1a, 0x4d, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41, 0x6c, 0x66, 0x79, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x37, 0x0a, 0x09, 0x54, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x49, 0x0a, 0x03,
	0x4d, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x72, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x1a, 0x2e, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_conf_alfy_proto_rawDescOnce sync.Once
	file_internal_conf_alfy_proto_rawDescData = file_internal_conf_alfy_proto_rawDesc
)

func file_internal_conf_alfy_proto_rawDescGZIP() []byte {
	file_internal_conf_alfy_proto_rawDescOnce.Do(func() {
		file_internal_conf_alfy_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_conf_alfy_proto_rawDescData)
	})
	return file_internal_conf_alfy_proto_rawDescData
}

var file_internal_conf_alfy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_conf_alfy_proto_goTypes = []interface{}{
	(*Alfy)(nil),            // 0: conf.Alfy
	(*Alfy_Items)(nil),      // 1: conf.Alfy.Items
	nil,                     // 2: conf.Alfy.Items.ModsEntry
	nil,                     // 3: conf.Alfy.Items.TextEntry
	(*Alfy_Items_Mod)(nil),  // 4: conf.Alfy.Items.Mod
	(*Alfy_Items_Icon)(nil), // 5: conf.Alfy.Items.Icon
}
var file_internal_conf_alfy_proto_depIdxs = []int32{
	1, // 0: conf.Alfy.items:type_name -> conf.Alfy.Items
	5, // 1: conf.Alfy.Items.icon:type_name -> conf.Alfy.Items.Icon
	2, // 2: conf.Alfy.Items.mods:type_name -> conf.Alfy.Items.ModsEntry
	3, // 3: conf.Alfy.Items.text:type_name -> conf.Alfy.Items.TextEntry
	4, // 4: conf.Alfy.Items.ModsEntry.value:type_name -> conf.Alfy.Items.Mod
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_conf_alfy_proto_init() }
func file_internal_conf_alfy_proto_init() {
	if File_internal_conf_alfy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_conf_alfy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alfy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_alfy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alfy_Items); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_alfy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alfy_Items_Mod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_alfy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alfy_Items_Icon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_conf_alfy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_alfy_proto_goTypes,
		DependencyIndexes: file_internal_conf_alfy_proto_depIdxs,
		MessageInfos:      file_internal_conf_alfy_proto_msgTypes,
	}.Build()
	File_internal_conf_alfy_proto = out.File
	file_internal_conf_alfy_proto_rawDesc = nil
	file_internal_conf_alfy_proto_goTypes = nil
	file_internal_conf_alfy_proto_depIdxs = nil
}
