// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/conf/mvn.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mvn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Mvn_Results `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Success bool           `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *Mvn) Reset() {
	*x = Mvn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_mvn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mvn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mvn) ProtoMessage() {}

func (x *Mvn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_mvn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mvn.ProtoReflect.Descriptor instead.
func (*Mvn) Descriptor() ([]byte, []int) {
	return file_internal_conf_mvn_proto_rawDescGZIP(), []int{0}
}

func (x *Mvn) GetResults() []*Mvn_Results {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Mvn) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Mvn_Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Mvn_Results) Reset() {
	*x = Mvn_Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_mvn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mvn_Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mvn_Results) ProtoMessage() {}

func (x *Mvn_Results) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_mvn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mvn_Results.ProtoReflect.Descriptor instead.
func (*Mvn_Results) Descriptor() ([]byte, []int) {
	return file_internal_conf_mvn_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Mvn_Results) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mvn_Results) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Mvn_Results) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_internal_conf_mvn_proto protoreflect.FileDescriptor

var file_internal_conf_mvn_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f,
	0x6d, 0x76, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x22,
	0x95, 0x01, 0x0a, 0x03, 0x4d, 0x76, 0x6e, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e,
	0x4d, 0x76, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x47,
	0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_conf_mvn_proto_rawDescOnce sync.Once
	file_internal_conf_mvn_proto_rawDescData = file_internal_conf_mvn_proto_rawDesc
)

func file_internal_conf_mvn_proto_rawDescGZIP() []byte {
	file_internal_conf_mvn_proto_rawDescOnce.Do(func() {
		file_internal_conf_mvn_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_conf_mvn_proto_rawDescData)
	})
	return file_internal_conf_mvn_proto_rawDescData
}

var file_internal_conf_mvn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_conf_mvn_proto_goTypes = []interface{}{
	(*Mvn)(nil),         // 0: conf.Mvn
	(*Mvn_Results)(nil), // 1: conf.Mvn.Results
}
var file_internal_conf_mvn_proto_depIdxs = []int32{
	1, // 0: conf.Mvn.results:type_name -> conf.Mvn.Results
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_conf_mvn_proto_init() }
func file_internal_conf_mvn_proto_init() {
	if File_internal_conf_mvn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_conf_mvn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mvn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_mvn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mvn_Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_conf_mvn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_mvn_proto_goTypes,
		DependencyIndexes: file_internal_conf_mvn_proto_depIdxs,
		MessageInfos:      file_internal_conf_mvn_proto_msgTypes,
	}.Build()
	File_internal_conf_mvn_proto = out.File
	file_internal_conf_mvn_proto_rawDesc = nil
	file_internal_conf_mvn_proto_goTypes = nil
	file_internal_conf_mvn_proto_depIdxs = nil
}
