// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/conf/npm_old.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NpmOld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormData      *NpmOld_FORMDATA   `protobuf:"bytes,1,opt,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	Objects       []*NpmOld_OBJECTS  `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	Total         float64            `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	Time          string             `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Pagination    *NpmOld_PAGINATION `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Url           string             `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Csrftoken     string             `protobuf:"bytes,8,opt,name=csrftoken,proto3" json:"csrftoken,omitempty"`
	Notifications []string           `protobuf:"bytes,9,rep,name=notifications,proto3" json:"notifications,omitempty"`
	NpmExpansions []string           `protobuf:"bytes,10,rep,name=npmExpansions,proto3" json:"npmExpansions,omitempty"`
	User          *NpmOld_USER       `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *NpmOld) Reset() {
	*x = NpmOld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld) ProtoMessage() {}

func (x *NpmOld) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld.ProtoReflect.Descriptor instead.
func (*NpmOld) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0}
}

func (x *NpmOld) GetFormData() *NpmOld_FORMDATA {
	if x != nil {
		return x.FormData
	}
	return nil
}

func (x *NpmOld) GetObjects() []*NpmOld_OBJECTS {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *NpmOld) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NpmOld) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *NpmOld) GetPagination() *NpmOld_PAGINATION {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *NpmOld) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NpmOld) GetCsrftoken() string {
	if x != nil {
		return x.Csrftoken
	}
	return ""
}

func (x *NpmOld) GetNotifications() []string {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *NpmOld) GetNpmExpansions() []string {
	if x != nil {
		return x.NpmExpansions
	}
	return nil
}

func (x *NpmOld) GetUser() *NpmOld_USER {
	if x != nil {
		return x.User
	}
	return nil
}

type NpmOld_FORMDATA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search *NpmOld_FORMDATA_SEARCH `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *NpmOld_FORMDATA) Reset() {
	*x = NpmOld_FORMDATA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_FORMDATA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_FORMDATA) ProtoMessage() {}

func (x *NpmOld_FORMDATA) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_FORMDATA.ProtoReflect.Descriptor instead.
func (*NpmOld_FORMDATA) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NpmOld_FORMDATA) GetSearch() *NpmOld_FORMDATA_SEARCH {
	if x != nil {
		return x.Search
	}
	return nil
}

type NpmOld_OBJECTS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package     *NpmOld_OBJECTS_PACKAGE `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Score       *NpmOld_OBJECTS_SCORE   `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	SearchScore float64                 `protobuf:"fixed64,3,opt,name=searchScore,proto3" json:"searchScore,omitempty"`
}

func (x *NpmOld_OBJECTS) Reset() {
	*x = NpmOld_OBJECTS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS) ProtoMessage() {}

func (x *NpmOld_OBJECTS) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1}
}

func (x *NpmOld_OBJECTS) GetPackage() *NpmOld_OBJECTS_PACKAGE {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *NpmOld_OBJECTS) GetScore() *NpmOld_OBJECTS_SCORE {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *NpmOld_OBJECTS) GetSearchScore() float64 {
	if x != nil {
		return x.SearchScore
	}
	return 0
}

type NpmOld_PAGINATION struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PerPage float64 `protobuf:"fixed64,1,opt,name=perPage,proto3" json:"perPage,omitempty"`
	Page    float64 `protobuf:"fixed64,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *NpmOld_PAGINATION) Reset() {
	*x = NpmOld_PAGINATION{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_PAGINATION) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_PAGINATION) ProtoMessage() {}

func (x *NpmOld_PAGINATION) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_PAGINATION.ProtoReflect.Descriptor instead.
func (*NpmOld_PAGINATION) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 2}
}

func (x *NpmOld_PAGINATION) GetPerPage() float64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *NpmOld_PAGINATION) GetPage() float64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type NpmOld_USER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NpmOld_USER) Reset() {
	*x = NpmOld_USER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_USER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_USER) ProtoMessage() {}

func (x *NpmOld_USER) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_USER.ProtoReflect.Descriptor instead.
func (*NpmOld_USER) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 3}
}

type NpmOld_FORMDATA_SEARCH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Q *NpmOld_FORMDATA_SEARCH_Q `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
}

func (x *NpmOld_FORMDATA_SEARCH) Reset() {
	*x = NpmOld_FORMDATA_SEARCH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_FORMDATA_SEARCH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_FORMDATA_SEARCH) ProtoMessage() {}

func (x *NpmOld_FORMDATA_SEARCH) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_FORMDATA_SEARCH.ProtoReflect.Descriptor instead.
func (*NpmOld_FORMDATA_SEARCH) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *NpmOld_FORMDATA_SEARCH) GetQ() *NpmOld_FORMDATA_SEARCH_Q {
	if x != nil {
		return x.Q
	}
	return nil
}

type NpmOld_FORMDATA_SEARCH_Q struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NpmOld_FORMDATA_SEARCH_Q) Reset() {
	*x = NpmOld_FORMDATA_SEARCH_Q{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_FORMDATA_SEARCH_Q) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_FORMDATA_SEARCH_Q) ProtoMessage() {}

func (x *NpmOld_FORMDATA_SEARCH_Q) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_FORMDATA_SEARCH_Q.ProtoReflect.Descriptor instead.
func (*NpmOld_FORMDATA_SEARCH_Q) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *NpmOld_FORMDATA_SEARCH_Q) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NpmOld_OBJECTS_PACKAGE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string                                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scope             string                                `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Version           string                                `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description       string                                `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Keywords          []string                              `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Date              *NpmOld_OBJECTS_PACKAGE_DATE          `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Links             *NpmOld_OBJECTS_PACKAGE_LINKS         `protobuf:"bytes,7,opt,name=links,proto3" json:"links,omitempty"`
	Author            *NpmOld_OBJECTS_PACKAGE_AUTHOR        `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	Publisher         *NpmOld_OBJECTS_PACKAGE_PUBLISHER     `protobuf:"bytes,9,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Maintainers       []*NpmOld_OBJECTS_PACKAGE_MAINTAINERS `protobuf:"bytes,10,rep,name=maintainers,proto3" json:"maintainers,omitempty"`
	KeywordsTruncated bool                                  `protobuf:"varint,11,opt,name=keywordsTruncated,proto3" json:"keywordsTruncated,omitempty"`
}

func (x *NpmOld_OBJECTS_PACKAGE) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *NpmOld_OBJECTS_PACKAGE) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE) GetDate() *NpmOld_OBJECTS_PACKAGE_DATE {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE) GetLinks() *NpmOld_OBJECTS_PACKAGE_LINKS {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE) GetAuthor() *NpmOld_OBJECTS_PACKAGE_AUTHOR {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE) GetPublisher() *NpmOld_OBJECTS_PACKAGE_PUBLISHER {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE) GetMaintainers() []*NpmOld_OBJECTS_PACKAGE_MAINTAINERS {
	if x != nil {
		return x.Maintainers
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE) GetKeywordsTruncated() bool {
	if x != nil {
		return x.KeywordsTruncated
	}
	return false
}

type NpmOld_OBJECTS_SCORE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Final  float64                      `protobuf:"fixed64,1,opt,name=final,proto3" json:"final,omitempty"`
	Detail *NpmOld_OBJECTS_SCORE_DETAIL `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *NpmOld_OBJECTS_SCORE) Reset() {
	*x = NpmOld_OBJECTS_SCORE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_SCORE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_SCORE) ProtoMessage() {}

func (x *NpmOld_OBJECTS_SCORE) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_SCORE.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_SCORE) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *NpmOld_OBJECTS_SCORE) GetFinal() float64 {
	if x != nil {
		return x.Final
	}
	return 0
}

func (x *NpmOld_OBJECTS_SCORE) GetDetail() *NpmOld_OBJECTS_SCORE_DETAIL {
	if x != nil {
		return x.Detail
	}
	return nil
}

type NpmOld_OBJECTS_PACKAGE_DATE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  int64  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Rel string `protobuf:"bytes,2,opt,name=rel,proto3" json:"rel,omitempty"`
}

func (x *NpmOld_OBJECTS_PACKAGE_DATE) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE_DATE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE_DATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE_DATE) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE_DATE) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE_DATE.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE_DATE) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *NpmOld_OBJECTS_PACKAGE_DATE) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *NpmOld_OBJECTS_PACKAGE_DATE) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

type NpmOld_OBJECTS_PACKAGE_LINKS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Npm        string `protobuf:"bytes,1,opt,name=npm,proto3" json:"npm,omitempty"`
	Homepage   string `protobuf:"bytes,2,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Repository string `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Bugs       string `protobuf:"bytes,4,opt,name=bugs,proto3" json:"bugs,omitempty"`
}

func (x *NpmOld_OBJECTS_PACKAGE_LINKS) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE_LINKS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE_LINKS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE_LINKS) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE_LINKS) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE_LINKS.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE_LINKS) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0, 1}
}

func (x *NpmOld_OBJECTS_PACKAGE_LINKS) GetNpm() string {
	if x != nil {
		return x.Npm
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE_LINKS) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE_LINKS) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE_LINKS) GetBugs() string {
	if x != nil {
		return x.Bugs
	}
	return ""
}

type NpmOld_OBJECTS_PACKAGE_AUTHOR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NpmOld_OBJECTS_PACKAGE_AUTHOR) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE_AUTHOR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE_AUTHOR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE_AUTHOR) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE_AUTHOR) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE_AUTHOR.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE_AUTHOR) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0, 2}
}

func (x *NpmOld_OBJECTS_PACKAGE_AUTHOR) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NpmOld_OBJECTS_PACKAGE_PUBLISHER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string                                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatars *NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS `protobuf:"bytes,2,opt,name=avatars,proto3" json:"avatars,omitempty"`
	Created *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Email   string                                    `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE_PUBLISHER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE_PUBLISHER) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE_PUBLISHER.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE_PUBLISHER) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0, 3}
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER) GetAvatars() *NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS {
	if x != nil {
		return x.Avatars
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER) GetCreated() *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type NpmOld_OBJECTS_PACKAGE_MAINTAINERS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *NpmOld_OBJECTS_PACKAGE_MAINTAINERS) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE_MAINTAINERS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE_MAINTAINERS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE_MAINTAINERS) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE_MAINTAINERS) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE_MAINTAINERS.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE_MAINTAINERS) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0, 4}
}

func (x *NpmOld_OBJECTS_PACKAGE_MAINTAINERS) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE_MAINTAINERS) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Small  string `protobuf:"bytes,1,opt,name=small,proto3" json:"small,omitempty"`
	Medium string `protobuf:"bytes,2,opt,name=medium,proto3" json:"medium,omitempty"`
	Large  string `protobuf:"bytes,3,opt,name=large,proto3" json:"large,omitempty"`
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0, 3, 0}
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS) GetSmall() string {
	if x != nil {
		return x.Small
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS) GetLarge() string {
	if x != nil {
		return x.Large
	}
	return ""
}

type NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Rel string                                       `protobuf:"bytes,2,opt,name=rel,proto3" json:"rel,omitempty"`
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0, 3, 1}
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED) GetTs() *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

type NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS) Reset() {
	*x = NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS) ProtoMessage() {}

func (x *NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 0, 3, 1, 0}
}

type NpmOld_OBJECTS_SCORE_DETAIL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quality     float64 `protobuf:"fixed64,1,opt,name=quality,proto3" json:"quality,omitempty"`
	Popularity  float64 `protobuf:"fixed64,2,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Maintenance float64 `protobuf:"fixed64,3,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
}

func (x *NpmOld_OBJECTS_SCORE_DETAIL) Reset() {
	*x = NpmOld_OBJECTS_SCORE_DETAIL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_conf_npm_old_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NpmOld_OBJECTS_SCORE_DETAIL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmOld_OBJECTS_SCORE_DETAIL) ProtoMessage() {}

func (x *NpmOld_OBJECTS_SCORE_DETAIL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_npm_old_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmOld_OBJECTS_SCORE_DETAIL.ProtoReflect.Descriptor instead.
func (*NpmOld_OBJECTS_SCORE_DETAIL) Descriptor() ([]byte, []int) {
	return file_internal_conf_npm_old_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

func (x *NpmOld_OBJECTS_SCORE_DETAIL) GetQuality() float64 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *NpmOld_OBJECTS_SCORE_DETAIL) GetPopularity() float64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *NpmOld_OBJECTS_SCORE_DETAIL) GetMaintenance() float64 {
	if x != nil {
		return x.Maintenance
	}
	return 0
}

var File_internal_conf_npm_old_proto protoreflect.FileDescriptor

var file_internal_conf_npm_old_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f,
	0x6e, 0x70, 0x6d, 0x5f, 0x6f, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63,
	0x6f, 0x6e, 0x66, 0x22, 0x96, 0x10, 0x0a, 0x06, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x12, 0x32,
	0x0a, 0x09, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e,
	0x46, 0x4f, 0x52, 0x4d, 0x44, 0x41, 0x54, 0x41, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2e, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c,
	0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x50,
	0x41, 0x47, 0x49, 0x4e, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x73, 0x72, 0x66, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x73, 0x72, 0x66,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x6e,
	0x70, 0x6d, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x6e, 0x70, 0x6d, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x55, 0x53,
	0x45, 0x52, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x93, 0x01, 0x0a, 0x08, 0x46, 0x4f, 0x52,
	0x4d, 0x44, 0x41, 0x54, 0x41, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d,
	0x4f, 0x6c, 0x64, 0x2e, 0x46, 0x4f, 0x52, 0x4d, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x53, 0x45, 0x41,
	0x52, 0x43, 0x48, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x1a, 0x51, 0x0a, 0x06, 0x53,
	0x45, 0x41, 0x52, 0x43, 0x48, 0x12, 0x2c, 0x0a, 0x01, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x46,
	0x4f, 0x52, 0x4d, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x2e, 0x51,
	0x52, 0x01, 0x71, 0x1a, 0x19, 0x0a, 0x01, 0x51, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0xc7,
	0x0b, 0x0a, 0x07, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x12, 0x36, 0x0a, 0x07, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54,
	0x53, 0x2e, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e,
	0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x2e, 0x53, 0x43, 0x4f, 0x52, 0x45, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0xee, 0x08, 0x0a, 0x07, 0x50, 0x41, 0x43, 0x4b, 0x41,
	0x47, 0x45, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64,
	0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x2e, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45,
	0x2e, 0x44, 0x41, 0x54, 0x45, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x6c,
	0x69, 0x6e, 0x6b, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53,
	0x2e, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45, 0x2e, 0x4c, 0x49, 0x4e, 0x4b, 0x53, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x3b, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d,
	0x4f, 0x6c, 0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x2e, 0x50, 0x41, 0x43, 0x4b,
	0x41, 0x47, 0x45, 0x2e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x44, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d,
	0x4f, 0x6c, 0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x2e, 0x50, 0x41, 0x43, 0x4b,
	0x41, 0x47, 0x45, 0x2e, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x45, 0x52, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x0b, 0x6d, 0x61, 0x69, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45,
	0x43, 0x54, 0x53, 0x2e, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45, 0x2e, 0x4d, 0x41, 0x49, 0x4e,
	0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x53, 0x52, 0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x54, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x11, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x54, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x1a, 0x28, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x45, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x6c, 0x1a, 0x69, 0x0a, 0x05,
	0x4c, 0x49, 0x4e, 0x4b, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x70, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6e, 0x70, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x75, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x75, 0x67, 0x73, 0x1a, 0x1c, 0x0a, 0x06, 0x41, 0x55, 0x54, 0x48, 0x4f,
	0x52, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0xfe, 0x02, 0x0a, 0x09, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53,
	0x48, 0x45, 0x52, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x07, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e,
	0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x2e, 0x50,
	0x41, 0x43, 0x4b, 0x41, 0x47, 0x45, 0x2e, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x45, 0x52,
	0x2e, 0x41, 0x56, 0x41, 0x54, 0x41, 0x52, 0x53, 0x52, 0x07, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x73, 0x12, 0x48, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e, 0x70, 0x6d, 0x4f, 0x6c, 0x64,
	0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x2e, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45,
	0x2e, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x45, 0x52, 0x2e, 0x43, 0x52, 0x45, 0x41, 0x54,
	0x45, 0x44, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x1a, 0x4d, 0x0a, 0x07, 0x41, 0x56, 0x41, 0x54, 0x41, 0x52, 0x53, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6d, 0x61,
	0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61,
	0x72, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x65,
	0x1a, 0x64, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x12, 0x41, 0x0a, 0x02, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e,
	0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x2e, 0x50, 0x41,
	0x43, 0x4b, 0x41, 0x47, 0x45, 0x2e, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x45, 0x52, 0x2e,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x2e, 0x54, 0x53, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x6c,
	0x1a, 0x04, 0x0a, 0x02, 0x54, 0x53, 0x1a, 0x3f, 0x0a, 0x0b, 0x4d, 0x41, 0x49, 0x4e, 0x54, 0x41,
	0x49, 0x4e, 0x45, 0x52, 0x53, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0xbe, 0x01, 0x0a, 0x05, 0x53, 0x43, 0x4f, 0x52,
	0x45, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x39, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4e,
	0x70, 0x6d, 0x4f, 0x6c, 0x64, 0x2e, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x53, 0x2e, 0x53, 0x43,
	0x4f, 0x52, 0x45, 0x2e, 0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x1a, 0x64, 0x0a, 0x06, 0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x12, 0x18, 0x0a, 0x07,
	0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x71,
	0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x61, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x3a, 0x0a, 0x0a, 0x50, 0x41, 0x47, 0x49,
	0x4e, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x1a, 0x06, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_conf_npm_old_proto_rawDescOnce sync.Once
	file_internal_conf_npm_old_proto_rawDescData = file_internal_conf_npm_old_proto_rawDesc
)

func file_internal_conf_npm_old_proto_rawDescGZIP() []byte {
	file_internal_conf_npm_old_proto_rawDescOnce.Do(func() {
		file_internal_conf_npm_old_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_conf_npm_old_proto_rawDescData)
	})
	return file_internal_conf_npm_old_proto_rawDescData
}

var file_internal_conf_npm_old_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_conf_npm_old_proto_goTypes = []interface{}{
	(*NpmOld)(nil),                                      // 0: conf.NpmOld
	(*NpmOld_FORMDATA)(nil),                             // 1: conf.NpmOld.FORMDATA
	(*NpmOld_OBJECTS)(nil),                              // 2: conf.NpmOld.OBJECTS
	(*NpmOld_PAGINATION)(nil),                           // 3: conf.NpmOld.PAGINATION
	(*NpmOld_USER)(nil),                                 // 4: conf.NpmOld.USER
	(*NpmOld_FORMDATA_SEARCH)(nil),                      // 5: conf.NpmOld.FORMDATA.SEARCH
	(*NpmOld_FORMDATA_SEARCH_Q)(nil),                    // 6: conf.NpmOld.FORMDATA.SEARCH.Q
	(*NpmOld_OBJECTS_PACKAGE)(nil),                      // 7: conf.NpmOld.OBJECTS.PACKAGE
	(*NpmOld_OBJECTS_SCORE)(nil),                        // 8: conf.NpmOld.OBJECTS.SCORE
	(*NpmOld_OBJECTS_PACKAGE_DATE)(nil),                 // 9: conf.NpmOld.OBJECTS.PACKAGE.DATE
	(*NpmOld_OBJECTS_PACKAGE_LINKS)(nil),                // 10: conf.NpmOld.OBJECTS.PACKAGE.LINKS
	(*NpmOld_OBJECTS_PACKAGE_AUTHOR)(nil),               // 11: conf.NpmOld.OBJECTS.PACKAGE.AUTHOR
	(*NpmOld_OBJECTS_PACKAGE_PUBLISHER)(nil),            // 12: conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER
	(*NpmOld_OBJECTS_PACKAGE_MAINTAINERS)(nil),          // 13: conf.NpmOld.OBJECTS.PACKAGE.MAINTAINERS
	(*NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS)(nil),    // 14: conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.AVATARS
	(*NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED)(nil),    // 15: conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.CREATED
	(*NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS)(nil), // 16: conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.CREATED.TS
	(*NpmOld_OBJECTS_SCORE_DETAIL)(nil),                 // 17: conf.NpmOld.OBJECTS.SCORE.DETAIL
}
var file_internal_conf_npm_old_proto_depIdxs = []int32{
	1,  // 0: conf.NpmOld.form_data:type_name -> conf.NpmOld.FORMDATA
	2,  // 1: conf.NpmOld.objects:type_name -> conf.NpmOld.OBJECTS
	3,  // 2: conf.NpmOld.pagination:type_name -> conf.NpmOld.PAGINATION
	4,  // 3: conf.NpmOld.user:type_name -> conf.NpmOld.USER
	5,  // 4: conf.NpmOld.FORMDATA.search:type_name -> conf.NpmOld.FORMDATA.SEARCH
	7,  // 5: conf.NpmOld.OBJECTS.package:type_name -> conf.NpmOld.OBJECTS.PACKAGE
	8,  // 6: conf.NpmOld.OBJECTS.score:type_name -> conf.NpmOld.OBJECTS.SCORE
	6,  // 7: conf.NpmOld.FORMDATA.SEARCH.q:type_name -> conf.NpmOld.FORMDATA.SEARCH.Q
	9,  // 8: conf.NpmOld.OBJECTS.PACKAGE.date:type_name -> conf.NpmOld.OBJECTS.PACKAGE.DATE
	10, // 9: conf.NpmOld.OBJECTS.PACKAGE.links:type_name -> conf.NpmOld.OBJECTS.PACKAGE.LINKS
	11, // 10: conf.NpmOld.OBJECTS.PACKAGE.author:type_name -> conf.NpmOld.OBJECTS.PACKAGE.AUTHOR
	12, // 11: conf.NpmOld.OBJECTS.PACKAGE.publisher:type_name -> conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER
	13, // 12: conf.NpmOld.OBJECTS.PACKAGE.maintainers:type_name -> conf.NpmOld.OBJECTS.PACKAGE.MAINTAINERS
	17, // 13: conf.NpmOld.OBJECTS.SCORE.detail:type_name -> conf.NpmOld.OBJECTS.SCORE.DETAIL
	14, // 14: conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.avatars:type_name -> conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.AVATARS
	15, // 15: conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.created:type_name -> conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.CREATED
	16, // 16: conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.CREATED.ts:type_name -> conf.NpmOld.OBJECTS.PACKAGE.PUBLISHER.CREATED.TS
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_conf_npm_old_proto_init() }
func file_internal_conf_npm_old_proto_init() {
	if File_internal_conf_npm_old_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_conf_npm_old_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_FORMDATA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_PAGINATION); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_USER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_FORMDATA_SEARCH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_FORMDATA_SEARCH_Q); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_SCORE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE_DATE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE_LINKS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE_AUTHOR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE_PUBLISHER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE_MAINTAINERS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE_PUBLISHER_AVATARS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_PACKAGE_PUBLISHER_CREATED_TS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_conf_npm_old_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NpmOld_OBJECTS_SCORE_DETAIL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_conf_npm_old_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_npm_old_proto_goTypes,
		DependencyIndexes: file_internal_conf_npm_old_proto_depIdxs,
		MessageInfos:      file_internal_conf_npm_old_proto_msgTypes,
	}.Build()
	File_internal_conf_npm_old_proto = out.File
	file_internal_conf_npm_old_proto_rawDesc = nil
	file_internal_conf_npm_old_proto_goTypes = nil
	file_internal_conf_npm_old_proto_depIdxs = nil
}
